apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: defender-autorestart-role
  namespace: twistlock
rules:
- apiGroups:
  - apps
  resourceNames:
  - twistlock-defender-ds
  resources:
  - daemonsets
  verbs:
  - get
  - patch
