apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: defender-autorestart-rolebinding
  namespace: twistlock
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: defender-autorestart-role
subjects:
- kind: ServiceAccount
  name: defender-autorestart
  namespace: twistlock
